/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class py_connection_pool_udp_UDPEchoServer */

#ifndef _Included_py_connection_pool_udp_UDPEchoServer
#define _Included_py_connection_pool_udp_UDPEchoServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     py_connection_pool_udp_UDPEchoServer
 * Method:    startEchoServer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_py_connection_pool_udp_UDPEchoServer_startEchoServer
  (JNIEnv *, jobject, jint);

/*
 * Class:     py_connection_pool_udp_UDPEchoServer
 * Method:    stopEchoServer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_py_connection_pool_udp_UDPEchoServer_stopEchoServer
  (JNIEnv *, jobject, jint);

/*
 * Class:     py_connection_pool_udp_UDPEchoServer
 * Method:    pauseEchoServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_py_connection_pool_udp_UDPEchoServer_pauseEchoServer
  (JNIEnv *, jobject);

/*
 * Class:     py_connection_pool_udp_UDPEchoServer
 * Method:    reviveEchoServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_py_connection_pool_udp_UDPEchoServer_reviveEchoServer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
