name: CentOS 7 / JDK 8
on: 
  push:
  workflow_dispatch:
jobs:
  pengyun-build-job:
    runs-on: ubuntu-18.04
    container:
      image: centos:7
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'
      - name: Install required packages
        run: |
          yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          yum install -y net-tools maven thrift protobuf-compiler
          
      - name: Build with Maven
        run: |
          mvn versions:use-dep-version --batch-mode -DdepVersion=$(thrift --version | awk '{print $3}') -Dincludes=org.apache.thrift:libthrift
          mvn package --batch-mode -Dmaven.test.skip=true
      - name: test with Maven
        run: mvn --batch-mode test
