name: CentOS 8 / JDK 8
on: 
  workflow_dispatch:
jobs:
  pengyun-build-job:
    runs-on: ubuntu-18.04
    container:
      image: centos:8
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'
      - name: Install required packages
        run: |
          yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
          yum install -y net-tools maven compat-openssl10 protobuf-compile
          yum install -y https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/t/thrift-0.9.1-15.el7.x86_64.rpm
          
      - name: Build with Maven
        run: |
          mvn versions:use-dep-version --batch-mode -DdepVersion=$(thrift --version | awk '{print $3}') -Dincludes=org.apache.thrift:libthrift
          mvn package --batch-mode -Dmaven.test.skip=true
      - name: test with Maven
        run: mvn --batch-mode test
