name: CentOS 7 / JDK 8
on: 
  workflow_dispatch:
jobs:
  pengyun-build-job:
    runs-on: ubuntu-18.04
    container:
      image: centos:7.9.2009
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'
      - name: Check for dockerenv
        run: |
          ls
          javac -version
