name: Ubuntu 20 / JDK 11
on: 
  workflow_dispatch:
  push:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      
      - name: Install required packages
        run: sudo apt-get install -y thrift-compiler protobuf-compiler
      
      - name: Test packages
        run: thrift --version && protoc --version
      
      - name: Build with Maven
        run: |
          mvn versions:use-dep-version -DdepVersion=$(thrift --version | awk '{print $3}') -Dincludes=org.apache.thrift:libthrift
          mvn package -Dmaven.test.skip=true

      - name: test with Maven
        run: mvn test
        
      - run: echo "🍏 This job's status is ${{ job.status }}."
