name: Ubuntu 18
on: 
  workflow_dispatch:
  push:
jobs:
  pengyun-build-job:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'
      
      - name: Install required packages
        run: |
          apt-get install -y thrift-compiler protobuf-compiler
      
      - name: Build with Maven
        run: |
          mvn versions:use-dep-version --batch-mode -DdepVersion=$(thrift --version | awk '{print $3}') -Dincludes=org.apache.thrift:libthrift
          mvn package --batch-mode -Dmaven.test.skip=true

      - name: test with Maven
        run: mvn --batch-mode test
